### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Smudgge** [Cozy-Plugins/CozyTreasureHunt#6]
**Tasks**
- [x] `/treasure edit`
- [x] `/treasure find <optional treasure type>`
- [x] `/treasure set [treasure type]` Used to place a treasure at the location you are standing in.
- [x] `/treasure remove <optional all>` Used to remove a treasure closest to where you are standing with a 4 block radius. When using the optional all argument, it will display a confirm menu before removing all treasure locations.
- [x] `/treasure spawn` Used to spawn all the treasure blocks at the locations.
- [x] `/treasure unspawn` Stops respawning treasure from spawning as well as removing all treasure blocks.
