### ISSUE TITLE
Representing folders in the treasure editor GUI

### ISSUE THREAD

**Issue by Smudgge** [Cozy-Plugins/CozyTreasureHunt#7]
**Tasks**
- [x] When opening the treasure editor you can select the file.
- [x] Option to create files.
- [x] Option to create folders.
